[package]
name = "chat_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {workspace = true}
argon2 = { version = "0.5.3", features = ["std"] }
axum = {workspace = true}
chrono = {version = "0.4.38" , features = ["serde"]}
jwt-simple = {version = "0.12.9",default-features = false,  features = ["pure-rust"]}
serde = {workspace = true}
serde_yaml = {workspace = true}
sqlx = {workspace = true}
thiserror = {workspace = true}
tokio = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
serde_json = "1.0.116"

[dev-dependencies]
http-body-util = "0.1.1"
sqlx-db-tester = "0.4.0"
